
name: Print hello 

on:
  workflow_dispatch:
      

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Get Your Code
        uses: actions/checkout@v2

      - name: Say Hello to the World
        run: echo "Hello, World!"   

